firstPRWelcomeComment: >
  Thanks for opening this pull request! Please check out our contributing guidelines.

firstPRMergeComment: >
  Awesome work, congrats on your first merged pull request!

verifyTitles:
  titleRegexp: ^CATTY-[0-9]{3,4} .+$
  alwaysUsePrTitle: false
  validateEitherPrOrSingleCommitTitle: false
  statusTitle: "Validator"
  failureMessage: "Invalid ${type}. Expected: ${regex}. Actual: ${title}. Please correct message."
