jira:
  url: 'https://jira-test.catrob.at'
  status: 'Merged'
    
pull_request_title_check:
  regular_expression: '((CATTY|JENKINS)-[0-9]{1,3}) .*'
  
status_check:
  label: 'PO Review required'
  target_url: 'https://jira-test.catrob.at/browse/{issue}'
