name: "Check Runs"
on: [pull_request]

jobs:
  CheckRuns:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - uses: LouisBrunner/checks-action@v0.1.0
      if: always()
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
        name: Test XYZ
        conclusion: "action_required"
