name: prmerge-upload-crowdin

on:
  pull_request:
    types: [closed] 

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Upload Localization to Crowdin by fastlane
      if: github.event.pull_request.merged == true
      env:
        CROWDIN_KEY: ${{ secrets.CROWDIN_API }}
      run: curl -F "files[catty/Localizable.strings]=@src/Catty/Resources/Localization/en.lproj/Localizable.strings" -F "export_patterns[catty/Localizable.strings]=/catty/%osx_code%/%original_file_name%" https://api.crowdin.com/api/project/githubactionstest/update-file?key=$CROWDIN_KEY
