name: swiftlint

on:
  pull_request:
    paths:
      - '**/*.swift'

jobs:
  SwiftLint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: GitHub Action for SwiftLint
        uses: m-herold/action-swiftlint@3.1.1
        with:
          args: --config .swiftlint.yml --strict
        env:
          WORKING_DIRECTORY: src
